auth:
  defaultQuota:
    maxSessions:          10000
    maxIdleSessionTTL:    0
    maxPacketSize:        65535
    maxPacketIdentifiers: 10
    maxQueueSizeQoS0:     100
    maxQueueSizeQoS1:     100
    maxQueueSizeQoS2:     100
  services: services-dev.yml

  admin_principal:
    username: admin_name
    password: admin_password
    uuid: "e4f7f759-a7f0-4ae7-8140-766269e1c503"
    permissions:
      "#": [ PUB, SUB, RET ]

admin:
  socketPath: "sock/hummingbird.sock"

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 16
    connectionLimit: 1024
  - type: websocket
    transport:
      type: socket
      bindAddress: 0.0.0.0
      bindPort: 1884
      listenBacklog: 5
# - type: tls
#   transport:
#     type: socket
#     bindAddress: 0.0.0.0
#     bindPort: 8883
#     listenBacklog: 5
#   wantClientCert: true
#   crtFilePath: resources/hummingbird_server.crt
#   keyFilePath: resources/hummingbird_server.key

logging:
  level: INFO
  appenders:
    - type: console
