auth:
  defaultQuota:
    maxSessions:          10000
    maxIdleSessionTTL:    0
    maxPacketSize:        65535
    maxPacketIdentifiers: 10
    maxQueueSizeQoS0:     100
    maxQueueSizeQoS1:     100
    maxQueueSizeQoS2:     100
  service:
    gateway: GATEWAY
    key: KEY
    secret: SECRET
    timeout: 30000
    numThreads: 10

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 50
    connectionLimit: 102400

logging:
  level: INFO
  appenders:
    - type: console
