auth:
  defaultQuota:
    maxSessions:          10000
    maxIdleSessionTTL:    0
    maxPacketSize:        65535
    maxPacketIdentifiers: 10
    maxQueueSizeQoS0:     100
    maxQueueSizeQoS1:     100
    maxQueueSizeQoS2:     100
  services:
    - endpoint:
        gateway: GATEWAY
        key: KEY
        secret: SECRET
        timeout: 30000
        numThreads: 10
      password: GATEWAY_ADMIN_PASSWORD
      uuid: "8bbc5ea0-42d1-425b-87f3-baaabe78b71c"

  admin_principal:
    username: admin_name
    password: admin_password
    uuid: "e4f7f759-a7f0-4ae7-8140-766269e1c503"
    permissions:
      "#": [ PUB, SUB, RET ]

transports:
  - type: socket
    bindAddress: 0.0.0.0
    bindPort: 1883
    listenBacklog: 50
    connectionLimit: 102400

logging:
  level: INFO
  appenders:
    - type: console
